Lr 8
RabbiPaw/OOP pull request #21
Opened 2024-05-21 19:34 UTC by RabbiPaw

ЛР №8. Реализация игры в виде Команды.
Реализовать одну игру в виде команды. У каждой игры есть своя очередь (не потокобезопасная) команд этой игры и список игровых объектов. Выполнение метода Execute игры заключается в установке скопа игры как текущего для IoC и выполнении нескольких команд из очереди игры. Количество команд, которые выполняются из очереди игры зависит от кванта времени, выделенного этой игре. В начале метода Execute засекаем текущее время (использовать методы для вычисления точного времени), далее после выполнения одной команды опять засекаем время, если разница между текущем временем и моментом времени в начале выполнения команды Execute меньше, чем выделенный квант времени, то выполняем еще одну команду из очереди, в противном случае прекращаем выполнение команды Execute. Любые исключения выброшенные из команды должны перехватываться внутри команды Execute и передаваться в обработчик ExceptionHandler. Для ExceptionHandler необходимо определить обработчик “по умолчанию”, в случае, если подходящий обработчик не был найден, который пробрасывает отловленное исключение из метода Execute.
  
Задание:
Реализация Execute. 

Definition of Done критерии
Метод Execute устанавливает текущим Scope, соответствующий данной игре.
Количество выполненных команд игры ограничено выделенным квантом времени. Само значение кванта времени разрешается через IoC.
Исключения выбрасываемые командой отлавливаются и передаются в ExceptionHandler.
Определена стратегия по умолчанию для ситуации, когда не  найдена подходящая стратегия для пары (Команда,  Выброшенное исключение).

2024-05-22 11:21 UTC, RabbiPaw commented
#20 #19

2024-05-31 11:43 UTC, zaryanezrya requested changes

2024-05-31 11:43 UTC, zaryanezrya commented on spacebattle/SpaceBattle.Lib.Tests/EndPointTest.cs
1. Лишние файлы в PR
2. Варнинги

2024-05-31 13:07 UTC, RabbiPaw commented on spacebattle/SpaceBattle.Lib.Tests/EndPointTest.cs
Лишние файлы из-за работы с копией ветки 7-ой лабы. Или эти файлы удалять или ожидать судьбы ЛР 7

2024-06-03 04:37 UTC, closed without merging